// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvKpQwIvQ_wV2CdVj4vVcUFGncGfIsIWE',
    appId: '1:955111297133:web:12e8ca54dd2f0a92a76f64',
    messagingSenderId: '955111297133',
    projectId: 'flutter-app-39dc6',
    authDomain: 'flutter-app-39dc6.firebaseapp.com',
    storageBucket: 'flutter-app-39dc6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg_o3LywiOdgGNldXFLNMmBvbO966zGsw',
    appId: '1:955111297133:android:0c9588a12f77dbafa76f64',
    messagingSenderId: '955111297133',
    projectId: 'flutter-app-39dc6',
    storageBucket: 'flutter-app-39dc6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc4_lot4LFtX5rsyOU1Tdk63hQqeLioIk',
    appId: '1:955111297133:ios:0f4c6a9127adf7ada76f64',
    messagingSenderId: '955111297133',
    projectId: 'flutter-app-39dc6',
    storageBucket: 'flutter-app-39dc6.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc4_lot4LFtX5rsyOU1Tdk63hQqeLioIk',
    appId: '1:955111297133:ios:0f4c6a9127adf7ada76f64',
    messagingSenderId: '955111297133',
    projectId: 'flutter-app-39dc6',
    storageBucket: 'flutter-app-39dc6.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvKpQwIvQ_wV2CdVj4vVcUFGncGfIsIWE',
    appId: '1:955111297133:web:94825ce1c2d291bca76f64',
    messagingSenderId: '955111297133',
    projectId: 'flutter-app-39dc6',
    authDomain: 'flutter-app-39dc6.firebaseapp.com',
    storageBucket: 'flutter-app-39dc6.firebasestorage.app',
  );
}
